### ISSUE TITLE
Manage the app from a tablet

### ISSUE THREAD

**Issue by adb1012** [adb1012/GESPRO_Practica_2_Curso_2024_2025#15]

**Comment by adb1012** [comment]
¿Has hecho ya la interfaz para el inicio de sesión?

**Comment by sergiomigueel152** [comment]
> ¿Has hecho ya la interfaz para el inicio de sesión?

Sí, ya esta diseñado y programado. 
![login-and-signup-flat-ui-concept-design-vector](https://github.com/user-attachments/assets/7e6aceea-7101-4d88-b7c1-cc849bf365eb)
